### ISSUE TITLE
how  do you put test video into code ?

### ISSUE THREAD

**Issue by candyflossmh** [Ghostbird/Analogue-Gauge-Reader#2]
how  do you put test video into code ?

**Comment by Ghostbird** [comment]
Try to run the script. It should explain it.

**Comment by candyflossmh** [comment]
usage: gauge.py [-h] filename
gauge.py: error: the following arguments are required: filename

**Comment by candyflossmh** [comment]
> Try to run the script. It should explain it.
usage: gauge.py [-h] filename
gauge.py: error: the following arguments are required: filename

**Comment by candyflossmh** [comment]
I have tried to put filename="video2.mp4" into script but the message above comes up

**Comment by Ghostbird** [comment]
It seems you are unfamiliar with the notation.
`gauge.py [-h] filename`
means that you should type `gauge.py` followed by the filename, and that you can optionally follow it with `-h`.

This is a common command line tool notation, in this case provided by Python's `argparse` module.

**Comment by candyflossmh** [comment]
do you mind typing exactly what I need to write , sorry i am still having problems

**Comment by candyflossmh** [comment]
> do you mind typing exactly what I need to write , sorry i am still having problems

Python[62987:18247159] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f88a2183be0

**Comment by Ghostbird** [comment]
With your filename being `video2.mp4` you should type `gauge.py video2.mp4` However, from the error, I assume you already did that, and I cannot tell what would cause such an error.

Note that in this case I assume `gauge.py` and the `video2.mp4` are in the same directory.

**Comment by candyflossmh** [comment]
it plays the video and the red marker on the needle but then comes up with a large error 
2021-04-10 22:00:16.968 Python[63366:18285051] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb50b1a1750
2021-04-10 22:00:16.974 Python[63366:18285051] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb50b1a1750'
*** First throw call stack:........

**Comment by candyflossmh** [comment]
I think the issue was that I was using a Mac. I now have a new runtime error which says :
Mean of empty slice 
out=out, **kwargs
and then leads to invalid value encountered in double_scalars
@Ghostbird do you know how to fix this

**Comment by Ghostbird** [comment]
Odd that it would not work on a Mac. As far as I know, all the libraries I used are cross platform. This was developed on Debian.
For you current error:
If you want to find what's wrong, put a breakpoint on line 141, which is the only line in the file that calls `np.mean`. Check the `data[i-n:i]` and `data[i+1:i+1+n]` should both contain at least one value. Apparently part of the data is unexpectedly empty there.
I thought the check in line 137 ` len(data) <= i + n:` was enough to prevent that issue, but apparently I was mistaken.
You could change line 137 to: `if len([x[1] for x in data[i+1:i+1+n]]) == 0 or len([x[1] for x in data[i-n:i]]) == 0:` and that should probably prevent the error. However, the error might be indicative of an actual problem in your data, and then you might still end up with errors later.

**Comment by Ghostbird** [comment]
I just found that there's several errors. I'll try to fix it over the weekend.

**Comment by Ghostbird** [comment]
Should work better now. Curve fitting doesn't yet work.
